### ISSUE TITLE
Unexpected error fetching porscheconnect data: 'nickName'

### ISSUE THREAD

**Issue by browetd** [CJNE/ha-porscheconnect#102]
## Configuration

```yaml
None... Using integration menu (login successful but error related to the Nickname)
```

## Describe the bug

Error while loading the integration... Integration not loaded correctly.  Removing/adding the integration did not fix the issue.

## Debug log

```text

-------------------------------------------------------------------
porscheconnect
Version: 0.0.8
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/cjne/ha-porscheconnect/issues
-------------------------------------------------------------------

2022-07-23 17:26:48 DEBUG (MainThread) [custom_components.porscheconnect] Saving tokens
2022-07-23 17:26:48 DEBUG (MainThread) [custom_components.porscheconnect] Init new data update coordinator
2022-07-23 17:26:50 INFO (MainThread) [custom_components.porscheconnect] User is authorized for vehicle vin WP1XXXXXXXX
2022-07-23 17:26:50 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for tahoma using this method at custom_components/tahoma/__init__.py, line 141: device_registry = await dr.async_get_registry(hass)
2022-07-23 17:26:50 DEBUG (MainThread) [custom_components.porscheconnect] Fetching initial data for vehicle WP1XXXXXXXX
2022-07-23 17:26:50 ERROR (MainThread) [custom_components.porscheconnect] Unexpected error fetching porscheconnect data: 'nickName'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/porscheconnect/__init__.py", line 187, in _async_update_data
    vehicle["name"] = summary["nickName"] or summary["modelDescription"]
KeyError: 'nickName'
2022-07-23 17:26:50 DEBUG (MainThread) [custom_components.porscheconnect] Finished fetching porscheconnect data in 2.574 seconds (success: False)

```

**Comment by browetd** [comment]
Fixed with new release...
