### ISSUE TITLE
User is not granted access to vehicle VIN

### ISSUE THREAD

**Issue by laur3ns** [CJNE/ha-porscheconnect#147]
No cars (devices/entities) show up and logs shows this error:

This error originated from a custom integration.

Logger: custom_components.porscheconnect
Source: custom_components/porscheconnect/__init__.py:100
Integration: Porsche Connect (documentation, issues)
First occurred: 20:48:19 (2 occurrences)
Last logged: 20:51:02

User is not granted access to vehicle VIN WP0ZZZXXXXXXXXXXX, reason

(end)

Any clue? My Porsche app and site work fine.

**Comment by laur3ns** [comment]
In latest version*

```
This error originated from a custom integration.

Logger: custom_components.porscheconnect
Source: custom_components/porscheconnect/__init__.py:100
Integration: Porsche Connect (documentation, issues)
First occurred: January 23, 2023 at 11:33:25 (2 occurrences)
Last logged: 20:20:11

User is not granted access to vehicle VIN WP0ZZZ98ZMS283460, reason


Logger: homeassistant.config_entries
Source: config_entries.py:1133
First occurred: 20:20:02 (1 occurrences)
Last logged: 20:20:02

Config entry 'lv@alp.hn' for porscheconnect integration not ready yet: string indices must be integers; Retrying in background

This error originated from a custom integration.

Logger: custom_components.porscheconnect
Source: custom_components/porscheconnect/__init__.py:193
Integration: Porsche Connect (documentation, issues)
First occurred: 20:20:02 (1 occurrences)
Last logged: 20:20:02

Unexpected error fetching porscheconnect data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/porscheconnect/__init__.py", line 193, in _async_update_data
    vin = vehicle["vin"]
TypeError: string indices must be integers


```

*) Version info:

Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

**Comment by fredriklj** [comment]
We're back to square one, cf. #242 and reopen any new issues.
