### ISSUE TITLE
permissions check not working anymore

### ISSUE THREAD

**Issue by kgroshert** [CJNE/ha-porscheconnect#172]
ha-porscheconnect cannot get the permissions for the VIN anymore. API change maybe?
Taking out the function call in ha-porscheconnect//custom_components/porscheconnect)/__init__.py will makes it work temporarily (lines 194-201).

Trying from the pyporscheconnectapi CLI (v0.0.25):

```
porschecli -e me@mail.com -p xxx permissions -a

None
Traceback (most recent call last):
  File "/usr/local/bin/porschecli", line 10, in <module>
    sys.exit(cli.cli())
  File "/usr/local/lib/python3.7/dist-packages/pyporscheconnectapi/cli.py", line 268, in cli
    loop.run_until_complete(main(args))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/pyporscheconnectapi/cli.py", line 73, in main
    data = await client.isAllowed(vin)
  File "/usr/local/lib/python3.7/dist-packages/pyporscheconnectapi/client.py", line 430, in isAllowed
    reason = service_status.get(
AttributeError: 'NoneType' object has no attribute 'get'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f99a40ec748>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f99a41048d0>, 3743445.337643096)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f99a40ec780>
```

**Comment by barto64** [comment]
Same here, integration is not working :(

**Comment by bedfordpckid** [comment]
The integration stopped working for me with the installation of the latest release of Home Assistant

**Comment by davidjac** [comment]
Yep same.

**Comment by midnightsurfer** [comment]
Not sure if it’s the same but yes a few days ago ceased working and no amount of reloading or rebooting fixes it 
![IMG_8748](https://user-images.githubusercontent.com/53126118/233491536-6af8adae-2139-4b81-a716-c10677f198b0.jpeg)

**Comment by fredriklj** [comment]
https://github.com/CJNE/pyporscheconnectapi/pull/22
