### ISSUE TITLE
NoneType error 

### ISSUE THREAD

**Issue by midnightsurfer** [CJNE/ha-porscheconnect#174]
## Configuration

```yaml
Add your logs here.
```

## Description

a nonetype error has consistently prevented operation for a few weeks now. Same error, causes all sensors to be unavailable. Tried uninstalling and reinstalling. 

## debug Logs 

```text

Logger: custom_components.porscheconnect
Source: custom_components/porscheconnect/__init__.py:194 
Integration: Porsche Connect ([documentation](https://github.com/CJNE/ha-porscheconnect), [issues](https://github.com/CJNE/ha-porscheconnect/issues)) 
First occurred: 12:00:48 (8 occurrences) 
Last logged: 12:02:39

Unexpected error fetching porscheconnect data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/porscheconnect/__init__.py", line 194, in _async_update_data
    permission_for_vin = await self.controller.isAllowed(vin)
  File "/usr/local/lib/python3.10/site-packages/pyporscheconnectapi/client.py", line 430, in isAllowed
    reason = service_status.get(
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by CJNE** [comment]
Version 0.0.13 was just release, it should fix this issue, re-open if you still have issues with the new version 👍
