### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by woozar** [CJNE/ha-porscheconnect#218]
I have got a new error (at least for me it is new)

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/porscheconnect/init.py", line 215, in _async_update_data
vehicle["services"] = await self.controller.getServices(vin)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pyporscheconnectapi/client.py", line 488, in getServices
is_privacy = data['vehicleServiceEnabledMap']['VSR'] == 'DISABLED'
~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'vehicleServiceEnabledMap'

**Comment by vidartorkilseng** [comment]
Integration has worked ok, but now the error below. 

Unexpected error fetching porscheconnect data: 'vehicleServiceEnabledMap'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/__init__.py", line 215, in _async_update_data
    vehicle["services"] = await self.controller.getServices(vin)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyporscheconnectapi/client.py", line 488, in getServices
    is_privacy = data['vehicleServiceEnabledMap']['VSR'] == 'DISABLED'
                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'vehicleServiceEnabledMap'

**Comment by fredriklj** [comment]
Can you please try #217 ?

**Comment by woozar** [comment]
> Can you please try #217 ?

I do not really understand what you mean. Is this an update? If so, my HACS does not offer it to me. I am up to date with 0.0.17

**Comment by vidartorkilseng** [comment]
#217 fixed the problem, thanks.

**Comment by woozar** [comment]
@fredriklj, @CJNE will #217 be merged any time soon?

**Comment by CJNE** [comment]
Yes, merging now, thanks @fredriklj !
