### ISSUE TITLE
Error loading module : nickname (?? )

### ISSUE THREAD

**Issue by lucabacchipg** [CJNE/ha-porscheconnect#251]
Hello, i have this issue with component reload for my Taycan (changed mail/vin into code below)

2024-11-18 13:04:55.451 DEBUG (MainThread) [custom_components.porscheconnect] Init new data update coordinator
2024-11-18 13:04:55.452 DEBUG (MainThread) [custom_components.porscheconnect] <ConfigEntry entry_id=01JCXXTRAVWC44TA1PGVWJ575R version=1 domain=porscheconnect title=xxx@gmail.com state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>
2024-11-18 13:04:55.958 INFO (MainThread) [custom_components.porscheconnect] User is authorized for vehicle vin WP0ZZZY1ZNSAXXXX
2024-11-18 13:04:55.997 DEBUG (MainThread) [custom_components.porscheconnect] Fetching initial data for vehicle WP0ZZZY1ZNSA72400
2024-11-18 13:04:55.998 ERROR (MainThread) [custom_components.porscheconnect] Unexpected error fetching porscheconnect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/__init__.py", line 213, in _async_update_data
    vehicle["name"] = summary["nickName"] or summary["modelDescription"]
                      ~~~~~~~^^^^^^^^^^^^
KeyError: 'nickName'
2024-11-18 13:04:56.001 DEBUG (MainThread) [custom_components.porscheconnect] Finished fetching porscheconnect data in 0.549 seconds (success: False)

**Comment by fredriklj** [comment]
Please see #242. Expect a new release soon(ish).
