### ISSUE TITLE
Nickname Key not found

### ISSUE THREAD

**Issue by Dominik-Notzon** [CJNE/ha-porscheconnect#261]
## Version of the custom_component

0.0.18

## Configuration

```yaml

```

## Describe the bug

Trying to configure the integration fails with the error below.

## Debug log
```text

Logger: custom_components.porscheconnect
Quelle: helpers/update_coordinator.py:382
Integration: Porsche Connect ([Dokumentation](https://github.com/CJNE/ha-porscheconnect), [Probleme](https://github.com/CJNE/ha-porscheconnect/issues))
Erstmals aufgetreten: 16:40:16 (72 Vorkommnisse)
Zuletzt protokolliert: 18:03:21

Unexpected error fetching porscheconnect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/__init__.py", line 213, in _async_update_data
    vehicle["name"] = summary["nickName"] or summary["modelDescription"]
                      ~~~~~~~^^^^^^^^^^^^
KeyError: 'nickName'

```

**Comment by fredriklj** [comment]
Hi, you seem to be running the old version of the integration. Please checkout and try the new_api branch, or just wait a day or so before we make a new release.
