### ISSUE TITLE
Error when I press button “get current vehicle information”

### ISSUE THREAD

**Issue by gvisie** [CJNE/ha-porscheconnect#273]
I’m very happy with the integration working again!
But I get an error now. I don’t know or the error was there from the beginning of version 0.1.0

I get an error when I push the get_current_vehicle_information button:

Logger: homeassistant
Source: custom_components/porscheconnect/device_tracker.py:71
integration: Porsche Connect ([documentation](https://github.com/CJNE/ha-porscheconnect), [issues](https://github.com/CJNE/ha-porscheconnect/issues))
First occurred: December 5, 2024 at 8:07:09 PM (55 occurrences)
Last logged: 9:28:17 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/device_tracker.py", line 71, in extra_state_attributes
    data = {"updated_at": self.vehicle.location_updated_at}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyporscheconnectapi/vehicle.py", line 202, in location_updated_at
    datetime_object = datetime.strptime(datetime_str, '%Y-%m-%dT%H:%M:%SZ')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None

**Comment by fredriklj** [comment]
Hi! This is fixed upstream in the library and will be included in the next release. If you want, you can install the main branch directly from the repo and get rid of the error.
