### ISSUE TITLE
Unexpected error fetching porscheconnect

### ISSUE THREAD

**Issue by barto64** [CJNE/ha-porscheconnect#67]
Hello,

A of  11:41 CET today I am getting the below error every 5 minutes (on each pooling) and also all Prosche connect related entities appear as unavailable.

2022-02-04 11:44:05 ERROR (MainThread) [custom_components.porscheconnect] Unexpected error fetching porscheconnect data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/porscheconnect/__init__.py", line 218, in _async_update_data
    vdata = await self._update_data_for_vehicle(vehicle)
  File "/config/custom_components/porscheconnect/__init__.py", line 145, in _update_data_for_vehicle
    **await self.controller.getStoredOverview(vin),
  File "/usr/local/lib/python3.9/site-packages/pyporscheconnectapi/client.py", line 418, in getStoredOverview
    data = await self._connection.get(
  File "/usr/local/lib/python3.9/site-packages/pyporscheconnectapi/connection.py", line 183, in get
    return await resp.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by barto64** [comment]
Please discard it, apologies, it looks like after reboot it is working fine again.

**Comment by barto64** [comment]
Re-opening the issue. After the reboot made because a new HA version it worked, but not too late afterwoards started to happen again every 5 minutes. Something may have changed at HA or Porsche side. Thanks

**Comment by CJNE** [comment]
I'm not seeing this problem, is it possible this was a temporary error on their backend or do you still have this?

**Comment by barto64** [comment]
Thanks for answering. No, i am not longer seeing it, it may has been as you said a temporary thing.

**Comment by barto64** [comment]
No more errors happened
